<!doctype html>
<html lang="en">
<head>
<script src='https://www.google.com/recaptcha/api.js'></script>
</head>
<body>
<pre>
<?php
    echo date("Y-m-d h:i:s");
?>
</pre>
<form method="post" action="/" id="userTag">
<div class="form-group">
    <label for="fname">First Name:</label>
    <input name="fname" id="fname" type="text" required />
</div>
<div class="form-group">
    <label for="fname">Last Name:</label>
    <input name="lname" id="lname" type="text" required />
</div>
<div class="form-group">
    <label for="phone">Phone:</label>
    <input name="phone" id="phone" type="text" required />
</div>
<div class="form-group">
    <label for="email">Email:</label> 
    <input name="email" id="email" type="email" required />
</div>
<input name="lat" id="lat" type="hidden" value="" />
<input name="lng" id="lng" type="hidden" value="" />

<div id="emplacementRecaptcha"></div>

<button
class="g-recaptcha"
data-sitekey="6LcIl0sUAAAAAOgcx5_9n4EZNRzCcjH2ExBeRY39"
data-callback="YourOnSubmitFn">
Submit
</button>
<button type="submit" class="btn btn-primary" id="submitTag">Submit</button>
</form>

<a href="#" class="btn btn-dhl remove-tag-btn" id="95">Yes</a>

</body>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"/></script>
<script src="//ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>

<script type="text/javascript">
    $( document ).ready(function() {
        // Handler for .ready() called.
        $("#userTag").submit(function(e){
             e.preventDefault();
        });

        $('.remove-tag-btn').on('click',function(e){
            var id = $(this).attr('id');
            
            $.ajax({
                type: "POST",
                dataType: "json",
                url: '/removetag',
                data:{
                   id:id                   
                },
                success: function (data) {	
                    $(this).attr('id','');

                },
                error: function(jqXHR, text, error){

                }
            });    
   
        })


        $("#submitTag").click(function(e){
            //e.preventDefault();
           
            
            if( $('#fname').val() != "" && $('#lname').val() != "" && $('#phone').val() != "" && $('#email').val() != ''){
                $.ajax({
		    	type: "POST",
    			url: '/addtag',
	    		data:{
                   fname:$('#fname').val(),
                   lname:$('#lname').val(),
                   phone:$('#phone').val(),
                   email:$("#email").val(),     
                   lat:$("#lat").val(),
                   lng:$("#lng").val()
                },
		    	success: function (data) {	
			    	// Inserting html into the result div on success
                    //$('#results').html(data);
                    console.log(data);
			    },
			    error: function(jqXHR, text, error){
                    // Displaying if there are any errors
                	$('#result').html(error);           
                }
            });    
            }
            
           
         });
    });

</script>




</html>